package com.altrium.export;

import com.altrium.review.Rating;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Map;

/**
 * The spreadsheet half of feature 19 (Apache POI).
 *
 * <h2>Two sheets, and a cover block on the first</h2>
 *
 * <p>The cover is not decoration. A spreadsheet leaves the system and is then read by somebody
 * with no way to ask it what it covered - so the cycle, the scope, who ran it and when are
 * written into the file itself. A workbook of numbers with no header is the one that gets
 * emailed on and misread.
 *
 * <p>Counts are written as numbers rather than text, because the point of offering XLSX at all
 * is that somebody will sum and sort them. A column of strings that look like numbers is the
 * usual reason an export has to be redone by hand.
 */
@Component
public class XlsxExporter {

    private static final DateTimeFormatter STAMP =
            DateTimeFormatter.ofPattern("d MMMM yyyy, HH:mm").withZone(ZoneId.systemDefault());

    private static final String[] COLUMNS = {
            "Department", "Under review", "Self-reviews in", "Manager reviews in",
            "Ratings set", "Shared with employee"
    };

    public byte[] render(ExportService.ExportReport report) {
        try (Workbook workbook = new XSSFWorkbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            CellStyle bold = boldStyle(workbook);
            CellStyle header = headerStyle(workbook);

            progressSheet(workbook, report, bold, header);
            ratingsSheet(workbook, report, header);

            workbook.write(out);
            return out.toByteArray();
        } catch (IOException e) {
            // In-memory throughout; an IOException here is a bug rather than a disk that filled.
            throw new UncheckedIOException("Could not write the export workbook", e);
        }
    }

    private void progressSheet(Workbook workbook, ExportService.ExportReport report,
                               CellStyle bold, CellStyle header) {
        Sheet sheet = workbook.createSheet("Progress");

        int r = 0;
        r = labelled(sheet, r, "Altrium review cycle", report.cycle().label(), bold);
        r = labelled(sheet, r, "Report for", report.audience(), bold);
        r = labelled(sheet, r, "Covers", report.scopeNote(), bold);
        r = labelled(sheet, r, "Generated", STAMP.format(report.generatedAt()), bold);
        r = labelled(sheet, r, "Generated by", report.generatedFor(), bold);
        r++;

        Row headings = sheet.createRow(r++);
        for (int c = 0; c < COLUMNS.length; c++) {
            Cell cell = headings.createCell(c);
            cell.setCellValue(COLUMNS[c]);
            cell.setCellStyle(header);
        }

        for (ExportService.DepartmentRow row : report.departments()) {
            Row line = sheet.createRow(r++);
            line.createCell(0).setCellValue(row.departmentName());
            line.createCell(1).setCellValue(row.participants());
            line.createCell(2).setCellValue(row.selfReviewsSubmitted());
            line.createCell(3).setCellValue(row.managerReviewsSubmitted());
            line.createCell(4).setCellValue(row.ratingsSet());
            line.createCell(5).setCellValue(row.ratingsReleased());
        }

        if (report.departments().isEmpty()) {
            // Said in words rather than left as an empty grid. An export with no rows and no
            // explanation reads as a broken report, and the usual next step is to run it again.
            sheet.createRow(r).createCell(0)
                    .setCellValue("No departments are in scope for this cycle.");
        }

        for (int c = 0; c < COLUMNS.length; c++) {
            sheet.autoSizeColumn(c);
        }
    }

    /**
     * The distribution, across everybody in scope and broken down by nothing.
     *
     * <p>A department column here would be one keystroke for whoever opens the file and a
     * disclosure for a department of one (P-7.5). The sheet does not carry the data to build it.
     */
    private void ratingsSheet(Workbook workbook, ExportService.ExportReport report,
                              CellStyle header) {
        Sheet sheet = workbook.createSheet("Ratings");

        Row headings = sheet.createRow(0);
        Cell rating = headings.createCell(0);
        rating.setCellValue("Rating");
        rating.setCellStyle(header);
        Cell people = headings.createCell(1);
        people.setCellValue("People");
        people.setCellStyle(header);

        int r = 1;
        for (Rating value : Rating.values()) {
            Map<Rating, Long> distribution = report.ratingDistribution();
            Row line = sheet.createRow(r++);
            line.createCell(0).setCellValue(label(value));
            // A rating nobody received is written as 0 rather than left blank. On an aggregate
            // the reader is entitled to, absent can only mean nobody, and a blank cell in a
            // spreadsheet reads as missing data.
            line.createCell(1).setCellValue(distribution.getOrDefault(value, 0L));
        }

        sheet.autoSizeColumn(0);
        sheet.autoSizeColumn(1);
    }

    private static String label(Rating rating) {
        return switch (rating) {
            case NEEDS_IMPROVEMENT -> "Needs improvement";
            case MEETS_EXPECTATIONS -> "Meets expectations";
            case EXCEEDS_EXPECTATIONS -> "Exceeds expectations";
        };
    }

    private static int labelled(Sheet sheet, int rowIndex, String label, String value,
                                CellStyle bold) {
        Row row = sheet.createRow(rowIndex);
        Cell key = row.createCell(0);
        key.setCellValue(label);
        key.setCellStyle(bold);
        row.createCell(1).setCellValue(value);
        return rowIndex + 1;
    }

    private static CellStyle boldStyle(Workbook workbook) {
        Font font = workbook.createFont();
        font.setBold(true);
        CellStyle style = workbook.createCellStyle();
        style.setFont(font);
        return style;
    }

    private static CellStyle headerStyle(Workbook workbook) {
        CellStyle style = boldStyle(workbook);
        style.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setBorderBottom(BorderStyle.THIN);
        return style;
    }
}
